services:
  # db:
  #   image: postgres:16
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: phoenix_deploy_test_dev
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #     - /etc/localtime:/etc/localtime:ro
  #   ports:
  #     - 5432:5432

  app:
    command: bash #-c "mix deps.get && mix phx.server"
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    
    environment:
      - HISTFILE=/usr/local/hist/.bash_history
    # depends_on:
    #   - db
    volumes:
      - .:/app
      - bash_history:/usr/local/hist
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 4000:4000

volumes:
  bash_history:
  # postgres:
